on: push
jobs:
  github-actions-environment-variables-ubuntu:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PARAMS: repo=${{ github.GITHUB_REPOSITORY }}&sha=${{ github.GITHUB_SHA }}$ref=${{ github.GITHUB_REF }}
    steps:
      - name: List of the GitHub Actions environment variables
        run: env
  curl:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PARAMS: repo=${{ github.GITHUB_REPOSITORY }}&sha=${{ github.GITHUB_SHA }}$ref=${{ github.GITHUB_REF }}
    steps:
    - name: curl
      uses: wei/curl@v1
      with:
        args: -X GET "http://sandbox.zebrajaeger.de?${PARAMS}&token=${TOKEN}"
