on: push
jobs:
  curl:
    runs-on: ubuntu-latest
    env:
      FOO: ${{ secrets.GITHUB_TOKEN }}
      PARAMS: ${{ GITHUB_REPOSITORY }}
    steps:
    - name: curl
      uses: wei/curl@v1
      with:
        args: -X GET "http://sandbox.zebrajaeger.de?$PARAMS"
