on: push
jobs:
  github-actions-environment-variables-ubuntu:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ github.token }}
      PARAMS: repo=${{ github.repository }}&sha=${{ github.sha }}$ref=${{ github.ref }}
    steps:
      - name: List of the GitHub Actions environment variables
        run: env
  curl:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ github.token }}
      PARAMS: repo=${{ github.repository }}&sha=${{ github.sha }}$ref=${{ github.ref }}
    steps:
    - name: curl
      uses: wei/curl@v1
      with:
        args: -X GET "http://sandbox.zebrajaeger.de?${PARAMS}"
