on: push
jobs:
  curl:
    runs-on: ubuntu-latest
    env:
      PARAMS: repo=${{env.GITHUB_REPOSITORY}}&sha=${{env.GITHUB_SHA}}&ref=${{env.GITHUB_REF}}&token=TODO
      FOO: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: curl
      uses: wei/curl@v1
      with:
        args: -X GET "http://sandbox.zebrajaeger.de?$PARAMS"
